# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controler_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(459, 888)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Chip1Btn = QtWidgets.QPushButton(Form)
        self.Chip1Btn.setObjectName("Chip1Btn")
        self.gridLayout_4.addWidget(self.Chip1Btn, 0, 0, 1, 1)
        self.Chip2Btn = QtWidgets.QPushButton(Form)
        self.Chip2Btn.setObjectName("Chip2Btn")
        self.gridLayout_4.addWidget(self.Chip2Btn, 0, 1, 1, 1)
        self.Chip3Btn = QtWidgets.QPushButton(Form)
        self.Chip3Btn.setObjectName("Chip3Btn")
        self.gridLayout_4.addWidget(self.Chip3Btn, 0, 2, 1, 1)
        self.Chip4Btn = QtWidgets.QPushButton(Form)
        self.Chip4Btn.setObjectName("Chip4Btn")
        self.gridLayout_4.addWidget(self.Chip4Btn, 1, 0, 1, 1)
        self.Chip5Btn = QtWidgets.QPushButton(Form)
        self.Chip5Btn.setObjectName("Chip5Btn")
        self.gridLayout_4.addWidget(self.Chip5Btn, 1, 1, 1, 1)
        self.Chip6Btn = QtWidgets.QPushButton(Form)
        self.Chip6Btn.setObjectName("Chip6Btn")
        self.gridLayout_4.addWidget(self.Chip6Btn, 1, 2, 1, 1)
        self.Chip7Btn = QtWidgets.QPushButton(Form)
        self.Chip7Btn.setObjectName("Chip7Btn")
        self.gridLayout_4.addWidget(self.Chip7Btn, 2, 0, 1, 1)
        self.Chip8Btn = QtWidgets.QPushButton(Form)
        self.Chip8Btn.setObjectName("Chip8Btn")
        self.gridLayout_4.addWidget(self.Chip8Btn, 2, 1, 1, 1)
        self.Chip9Btn = QtWidgets.QPushButton(Form)
        self.Chip9Btn.setObjectName("Chip9Btn")
        self.gridLayout_4.addWidget(self.Chip9Btn, 2, 2, 1, 1)
        self.Chip10Btn = QtWidgets.QPushButton(Form)
        self.Chip10Btn.setObjectName("Chip10Btn")
        self.gridLayout_4.addWidget(self.Chip10Btn, 3, 0, 1, 1)
        self.Chip11Btn = QtWidgets.QPushButton(Form)
        self.Chip11Btn.setObjectName("Chip11Btn")
        self.gridLayout_4.addWidget(self.Chip11Btn, 3, 1, 1, 1)
        self.Chip12Btn = QtWidgets.QPushButton(Form)
        self.Chip12Btn.setObjectName("Chip12Btn")
        self.gridLayout_4.addWidget(self.Chip12Btn, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.yPositiveBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yPositiveBtn.sizePolicy().hasHeightForWidth())
        self.yPositiveBtn.setSizePolicy(sizePolicy)
        self.yPositiveBtn.setObjectName("yPositiveBtn")
        self.gridLayout.addWidget(self.yPositiveBtn, 0, 1, 1, 1)
        self.xNegativeBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xNegativeBtn.sizePolicy().hasHeightForWidth())
        self.xNegativeBtn.setSizePolicy(sizePolicy)
        self.xNegativeBtn.setObjectName("xNegativeBtn")
        self.gridLayout.addWidget(self.xNegativeBtn, 1, 0, 1, 1)
        self.xPositiveBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xPositiveBtn.sizePolicy().hasHeightForWidth())
        self.xPositiveBtn.setSizePolicy(sizePolicy)
        self.xPositiveBtn.setObjectName("xPositiveBtn")
        self.gridLayout.addWidget(self.xPositiveBtn, 1, 2, 1, 1)
        self.yNegativeBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yNegativeBtn.sizePolicy().hasHeightForWidth())
        self.yNegativeBtn.setSizePolicy(sizePolicy)
        self.yNegativeBtn.setObjectName("yNegativeBtn")
        self.gridLayout.addWidget(self.yNegativeBtn, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.XYSpeedSlider = QtWidgets.QSlider(self.groupBox)
        self.XYSpeedSlider.setOrientation(QtCore.Qt.Vertical)
        self.XYSpeedSlider.setObjectName("XYSpeedSlider")
        self.verticalLayout_2.addWidget(self.XYSpeedSlider, 0, QtCore.Qt.AlignHCenter)
        self.XYSpeedLabel = QtWidgets.QLabel(self.groupBox)
        self.XYSpeedLabel.setObjectName("XYSpeedLabel")
        self.verticalLayout_2.addWidget(self.XYSpeedLabel, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.zPositiveBtn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zPositiveBtn.sizePolicy().hasHeightForWidth())
        self.zPositiveBtn.setSizePolicy(sizePolicy)
        self.zPositiveBtn.setObjectName("zPositiveBtn")
        self.verticalLayout_3.addWidget(self.zPositiveBtn, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.zNegativeBtn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zNegativeBtn.sizePolicy().hasHeightForWidth())
        self.zNegativeBtn.setSizePolicy(sizePolicy)
        self.zNegativeBtn.setObjectName("zNegativeBtn")
        self.verticalLayout_3.addWidget(self.zNegativeBtn, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ZSpeedSlider = QtWidgets.QSlider(self.groupBox_2)
        self.ZSpeedSlider.setOrientation(QtCore.Qt.Vertical)
        self.ZSpeedSlider.setObjectName("ZSpeedSlider")
        self.verticalLayout_4.addWidget(self.ZSpeedSlider, 0, QtCore.Qt.AlignHCenter)
        self.ZSpeedLabel = QtWidgets.QLabel(self.groupBox_2)
        self.ZSpeedLabel.setObjectName("ZSpeedLabel")
        self.verticalLayout_4.addWidget(self.ZSpeedLabel, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Chip1Btn.setText(_translate("Form", "芯片1"))
        self.Chip2Btn.setText(_translate("Form", "芯片2"))
        self.Chip3Btn.setText(_translate("Form", "芯片3"))
        self.Chip4Btn.setText(_translate("Form", "芯片4"))
        self.Chip5Btn.setText(_translate("Form", "芯片5"))
        self.Chip6Btn.setText(_translate("Form", "芯片6"))
        self.Chip7Btn.setText(_translate("Form", "芯片7"))
        self.Chip8Btn.setText(_translate("Form", "芯片8"))
        self.Chip9Btn.setText(_translate("Form", "芯片9"))
        self.Chip10Btn.setText(_translate("Form", "芯片10"))
        self.Chip11Btn.setText(_translate("Form", "芯片11"))
        self.Chip12Btn.setText(_translate("Form", "芯片12"))
        self.groupBox.setTitle(_translate("Form", "XY轴控制"))
        self.yPositiveBtn.setText(_translate("Form", "Y+"))
        self.xNegativeBtn.setText(_translate("Form", "X-"))
        self.xPositiveBtn.setText(_translate("Form", "X+"))
        self.yNegativeBtn.setText(_translate("Form", "Y-"))
        self.XYSpeedLabel.setText(_translate("Form", "TextLabel"))
        self.groupBox_2.setTitle(_translate("Form", "Z轴控制"))
        self.zPositiveBtn.setText(_translate("Form", "Z+"))
        self.zNegativeBtn.setText(_translate("Form", "Z-"))
        self.ZSpeedLabel.setText(_translate("Form", "TextLabel"))

