# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Image_analysis_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2111, 1252)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_21 = QtWidgets.QGridLayout(Form)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox.setStyleSheet("/*这是对QGroupBox的框样式进行设定*/\n"
"QGroupBox{\n"
"    \n"
"    border: 2px solid rgb(80,80,80);\n"
"    border-radius:6px;\n"
" margin-top: 0ex\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    rgb(0, 0, 0)\n"
"    subcontrol-origin: margin;\n"
"    \n"
"\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setStyleSheet(".QFrame {\n"
"\n"
"border-style: solid;\n"
"border-bottom: 2px solid;\n"
"    border-bottom-color: rgb(134, 130, 139);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.LinearEnhanceRadio = QtWidgets.QRadioButton(self.frame_2)
        self.LinearEnhanceRadio.setObjectName("LinearEnhanceRadio")
        self.gridLayout_3.addWidget(self.LinearEnhanceRadio, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setStyleSheet("QLabel {\n"
"border-style: solid;\n"
"border-color: red;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.LinearAlphaEdit = QtWidgets.QLineEdit(self.frame_2)
        self.LinearAlphaEdit.setObjectName("LinearAlphaEdit")
        self.horizontalLayout.addWidget(self.LinearAlphaEdit)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.LinearBetaEdit = QtWidgets.QLineEdit(self.frame_2)
        self.LinearBetaEdit.setObjectName("LinearBetaEdit")
        self.horizontalLayout_2.addWidget(self.LinearBetaEdit)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.NormEhhanceRadio = QtWidgets.QRadioButton(self.frame_2)
        self.NormEhhanceRadio.setObjectName("NormEhhanceRadio")
        self.gridLayout_3.addWidget(self.NormEhhanceRadio, 1, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setStyleSheet("QLabel {\n"
"border-style: solid;\n"
"border-color: red;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.NormAlphaEdit = QtWidgets.QLineEdit(self.frame_2)
        self.NormAlphaEdit.setObjectName("NormAlphaEdit")
        self.horizontalLayout_3.addWidget(self.NormAlphaEdit)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.NormBetaEdit = QtWidgets.QLineEdit(self.frame_2)
        self.NormBetaEdit.setObjectName("NormBetaEdit")
        self.horizontalLayout_6.addWidget(self.NormBetaEdit)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.GammaRadio = QtWidgets.QRadioButton(self.frame_2)
        self.GammaRadio.setObjectName("GammaRadio")
        self.gridLayout_3.addWidget(self.GammaRadio, 2, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gammaEdit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gammaEdit.sizePolicy().hasHeightForWidth())
        self.gammaEdit.setSizePolicy(sizePolicy)
        self.gammaEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gammaEdit.setObjectName("gammaEdit")
        self.horizontalLayout_7.addWidget(self.gammaEdit, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_7.setStretch(0, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 2, 2, 1, 1)
        self.equalizeHistRadio = QtWidgets.QRadioButton(self.frame_2)
        self.equalizeHistRadio.setObjectName("equalizeHistRadio")
        self.gridLayout_3.addWidget(self.equalizeHistRadio, 3, 0, 1, 2)
        self.CLAHERadio = QtWidgets.QRadioButton(self.frame_2)
        self.CLAHERadio.setObjectName("CLAHERadio")
        self.gridLayout_3.addWidget(self.CLAHERadio, 4, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.clipLimitEdit = QtWidgets.QLineEdit(self.frame_2)
        self.clipLimitEdit.setObjectName("clipLimitEdit")
        self.horizontalLayout_8.addWidget(self.clipLimitEdit)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.tileGridSizeEdit = QtWidgets.QLineEdit(self.frame_2)
        self.tileGridSizeEdit.setObjectName("tileGridSizeEdit")
        self.horizontalLayout_9.addWidget(self.tileGridSizeEdit)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 4, 1, 1, 2)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.gridLayout_3.setRowStretch(3, 1)
        self.gridLayout_3.setRowStretch(4, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.EnhanceBtn = QtWidgets.QPushButton(self.frame)
        self.EnhanceBtn.setObjectName("EnhanceBtn")
        self.gridLayout_2.addWidget(self.EnhanceBtn, 0, 0, 1, 1)
        self.ContrastImgBtn = QtWidgets.QPushButton(self.frame)
        self.ContrastImgBtn.setObjectName("ContrastImgBtn")
        self.gridLayout_2.addWidget(self.ContrastImgBtn, 0, 1, 1, 1)
        self.isSaveContrastImgCheck = QtWidgets.QCheckBox(self.frame)
        self.isSaveContrastImgCheck.setObjectName("isSaveContrastImgCheck")
        self.gridLayout_2.addWidget(self.isSaveContrastImgCheck, 0, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setStyleSheet("/*这是对QGroupBox的框样式进行设定*/\n"
"QGroupBox{\n"
"    \n"
"    border: 2px solid rgb(80,80,80);\n"
"    border-radius:6px;\n"
" margin-top: 0ex\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    rgb(0, 0, 0)\n"
"    subcontrol-origin: margin;\n"
"    \n"
"\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_7 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_7.setStyleSheet(".QFrame {\n"
"\n"
"border-style: solid;\n"
"border-bottom: 2px solid;\n"
"    border-bottom-color: rgb(134, 130, 139);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout.setObjectName("gridLayout")
        self.GaussBlurRadio = QtWidgets.QRadioButton(self.frame_7)
        self.GaussBlurRadio.setObjectName("GaussBlurRadio")
        self.gridLayout.addWidget(self.GaussBlurRadio, 2, 0, 1, 1)
        self.medianBlurRadio = QtWidgets.QRadioButton(self.frame_7)
        self.medianBlurRadio.setObjectName("medianBlurRadio")
        self.gridLayout.addWidget(self.medianBlurRadio, 1, 0, 1, 1)
        self.averageBlurRadio = QtWidgets.QRadioButton(self.frame_7)
        self.averageBlurRadio.setObjectName("averageBlurRadio")
        self.gridLayout.addWidget(self.averageBlurRadio, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.kernalEdit = QtWidgets.QLineEdit(self.frame_7)
        self.kernalEdit.setObjectName("kernalEdit")
        self.horizontalLayout_10.addWidget(self.kernalEdit, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 3)
        self.gridLayout.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.frame_7, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.blurBtn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blurBtn.sizePolicy().hasHeightForWidth())
        self.blurBtn.setSizePolicy(sizePolicy)
        self.blurBtn.setObjectName("blurBtn")
        self.horizontalLayout_13.addWidget(self.blurBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.BluredImgBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.BluredImgBtn.setObjectName("BluredImgBtn")
        self.horizontalLayout_13.addWidget(self.BluredImgBtn)
        self.isSaveBlurImgCheck = QtWidgets.QCheckBox(self.groupBox_2)
        self.isSaveBlurImgCheck.setObjectName("isSaveBlurImgCheck")
        self.horizontalLayout_13.addWidget(self.isSaveBlurImgCheck, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 1)
        self.horizontalLayout_13.setStretch(2, 2)
        self.gridLayout_8.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_3.setStyleSheet("/*这是对QGroupBox的框样式进行设定*/\n"
"QGroupBox{\n"
"    \n"
"    border: 2px solid rgb(80,80,80);\n"
"    border-radius:6px;\n"
" margin-top: 0ex\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    rgb(0, 0, 0)\n"
"    subcontrol-origin: margin;\n"
"    \n"
"\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_4.setStyleSheet(".QFrame {\n"
"\n"
"border-style: solid;\n"
"border-bottom: 2px solid;\n"
"    border-bottom-color: rgb(134, 130, 139);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.ThresholdRadio = QtWidgets.QRadioButton(self.frame_4)
        self.ThresholdRadio.setObjectName("ThresholdRadio")
        self.gridLayout_10.addWidget(self.ThresholdRadio, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.ThresholdValudEdit = QtWidgets.QLineEdit(self.frame_4)
        self.ThresholdValudEdit.setObjectName("ThresholdValudEdit")
        self.horizontalLayout_4.addWidget(self.ThresholdValudEdit)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.GaussThresholdRadio = QtWidgets.QRadioButton(self.frame_4)
        self.GaussThresholdRadio.setObjectName("GaussThresholdRadio")
        self.gridLayout_10.addWidget(self.GaussThresholdRadio, 1, 0, 1, 1)
        self.MeanThresholdRadio = QtWidgets.QRadioButton(self.frame_4)
        self.MeanThresholdRadio.setObjectName("MeanThresholdRadio")
        self.gridLayout_10.addWidget(self.MeanThresholdRadio, 2, 0, 1, 1)
        self.OTSUThresholdRadio = QtWidgets.QRadioButton(self.frame_4)
        self.OTSUThresholdRadio.setObjectName("OTSUThresholdRadio")
        self.gridLayout_10.addWidget(self.OTSUThresholdRadio, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.BlockSizeEdit = QtWidgets.QLineEdit(self.frame_4)
        self.BlockSizeEdit.setObjectName("BlockSizeEdit")
        self.horizontalLayout_5.addWidget(self.BlockSizeEdit)
        self.gridLayout_10.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.gridLayout_11.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ExecuteThresBtn = QtWidgets.QPushButton(self.frame_5)
        self.ExecuteThresBtn.setObjectName("ExecuteThresBtn")
        self.horizontalLayout_11.addWidget(self.ExecuteThresBtn)
        self.ThresImgBtn = QtWidgets.QPushButton(self.frame_5)
        self.ThresImgBtn.setObjectName("ThresImgBtn")
        self.horizontalLayout_11.addWidget(self.ThresImgBtn)
        self.isSaveThresImgCheck = QtWidgets.QCheckBox(self.frame_5)
        self.isSaveThresImgCheck.setObjectName("isSaveThresImgCheck")
        self.horizontalLayout_11.addWidget(self.isSaveThresImgCheck)
        self.gridLayout_11.addWidget(self.frame_5, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.RectificationBtn = QtWidgets.QPushButton(self.frame_6)
        self.RectificationBtn.setObjectName("RectificationBtn")
        self.gridLayout_12.addWidget(self.RectificationBtn, 0, 0, 1, 1)
        self.isSaveRectifyImgCheck = QtWidgets.QCheckBox(self.frame_6)
        self.isSaveRectifyImgCheck.setObjectName("isSaveRectifyImgCheck")
        self.gridLayout_12.addWidget(self.isSaveRectifyImgCheck, 0, 1, 1, 1)
        self.returnOrignalImgBtn = QtWidgets.QPushButton(self.frame_6)
        self.returnOrignalImgBtn.setObjectName("returnOrignalImgBtn")
        self.gridLayout_12.addWidget(self.returnOrignalImgBtn, 1, 0, 1, 1)
        self.HoughCircleBtn = QtWidgets.QPushButton(self.frame_6)
        self.HoughCircleBtn.setObjectName("HoughCircleBtn")
        self.gridLayout_12.addWidget(self.HoughCircleBtn, 1, 1, 1, 1)
        self.gridLayout_13.addWidget(self.frame_6, 3, 0, 1, 1)
        self.listView = QtWidgets.QListView(self.frame_3)
        self.listView.setObjectName("listView")
        self.gridLayout_13.addWidget(self.listView, 4, 0, 1, 1)
        self.gridLayout_21.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ShowImgLayout = QtWidgets.QGridLayout()
        self.ShowImgLayout.setObjectName("ShowImgLayout")
        self.gridLayout_9.addLayout(self.ShowImgLayout, 0, 0, 1, 2)
        self.HistImgLayout = QtWidgets.QGridLayout()
        self.HistImgLayout.setObjectName("HistImgLayout")
        self.gridLayout_9.addLayout(self.HistImgLayout, 1, 0, 1, 1)
        self.ROILayout = QtWidgets.QGridLayout()
        self.ROILayout.setObjectName("ROILayout")
        self.gridLayout_9.addLayout(self.ROILayout, 1, 1, 1, 1)
        self.gridLayout_9.setRowStretch(0, 2)
        self.gridLayout_9.setRowStretch(1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_9, 0, 1, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setStyleSheet("/*这是对QGroupBox的框样式进行设定*/\n"
"QGroupBox{\n"
"    \n"
"    border: 2px solid rgb(80,80,80);\n"
"    border-radius:6px;\n"
" margin-top: 0ex\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    rgb(0, 0, 0)\n"
"    subcontrol-origin: margin;\n"
"    \n"
"\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_9.setStyleSheet(".QFrame {\n"
"\n"
"border-style: solid;\n"
"border-bottom: 2px solid;\n"
"    border-bottom-color: rgb(134, 130, 139);\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_8 = QtWidgets.QFrame(self.frame_9)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_15.addWidget(self.label_5)
        self.MorphInterationEdit = QtWidgets.QLineEdit(self.frame_8)
        self.MorphInterationEdit.setObjectName("MorphInterationEdit")
        self.horizontalLayout_15.addWidget(self.MorphInterationEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 2, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.MorphRectRadio = QtWidgets.QRadioButton(self.frame_8)
        self.MorphRectRadio.setObjectName("MorphRectRadio")
        self.gridLayout_5.addWidget(self.MorphRectRadio, 0, 1, 1, 1)
        self.MorphElliRadio = QtWidgets.QRadioButton(self.frame_8)
        self.MorphElliRadio.setObjectName("MorphElliRadio")
        self.gridLayout_5.addWidget(self.MorphElliRadio, 1, 1, 1, 1)
        self.MorphCrossRadio = QtWidgets.QRadioButton(self.frame_8)
        self.MorphCrossRadio.setObjectName("MorphCrossRadio")
        self.gridLayout_5.addWidget(self.MorphCrossRadio, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.MorphKernelSizeEdit = QtWidgets.QLineEdit(self.frame_8)
        self.MorphKernelSizeEdit.setObjectName("MorphKernelSizeEdit")
        self.horizontalLayout_12.addWidget(self.MorphKernelSizeEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.isSaveMorphImgCheck = QtWidgets.QCheckBox(self.frame_8)
        self.isSaveMorphImgCheck.setObjectName("isSaveMorphImgCheck")
        self.gridLayout_6.addWidget(self.isSaveMorphImgCheck, 3, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame_8, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.BlackHatBtn = QtWidgets.QPushButton(self.frame_9)
        self.BlackHatBtn.setObjectName("BlackHatBtn")
        self.horizontalLayout_14.addWidget(self.BlackHatBtn)
        self.TopHatBtn = QtWidgets.QPushButton(self.frame_9)
        self.TopHatBtn.setObjectName("TopHatBtn")
        self.horizontalLayout_14.addWidget(self.TopHatBtn)
        self.DilationBtn = QtWidgets.QPushButton(self.frame_9)
        self.DilationBtn.setObjectName("DilationBtn")
        self.horizontalLayout_14.addWidget(self.DilationBtn)
        self.ErosionBtn = QtWidgets.QPushButton(self.frame_9)
        self.ErosionBtn.setObjectName("ErosionBtn")
        self.horizontalLayout_14.addWidget(self.ErosionBtn)
        self.gridLayout_14.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_9, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setStyleSheet("/*这是对QGroupBox的框样式进行设定*/\n"
"QGroupBox{\n"
"    \n"
"    border: 2px solid rgb(80,80,80);\n"
"    border-radius:6px;\n"
" margin-top: 0ex\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    rgb(0, 0, 0)\n"
"    subcontrol-origin: margin;\n"
"    \n"
"\n"
"}")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.FindRectBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.FindRectBtn.setObjectName("FindRectBtn")
        self.gridLayout_19.addWidget(self.FindRectBtn, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 2, 1, 1)
        self.gridLayout_21.setColumnStretch(0, 1)
        self.gridLayout_21.setColumnStretch(1, 5)
        self.gridLayout_21.setColumnStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LinearEnhanceRadio.setText(_translate("Form", "线性变换"))
        self.label_6.setText(_translate("Form", "alpha:"))
        self.label_7.setText(_translate("Form", "beta:"))
        self.NormEhhanceRadio.setText(_translate("Form", "正则变换"))
        self.label_8.setText(_translate("Form", "alpha:"))
        self.label_9.setText(_translate("Form", "beta:"))
        self.GammaRadio.setText(_translate("Form", "Gamma变换"))
        self.equalizeHistRadio.setText(_translate("Form", "全局变换"))
        self.CLAHERadio.setText(_translate("Form", "CLAHE变换"))
        self.label_10.setText(_translate("Form", "clipLimit:"))
        self.label_11.setText(_translate("Form", "tileGridSize:"))
        self.EnhanceBtn.setText(_translate("Form", "增强"))
        self.ContrastImgBtn.setText(_translate("Form", "对比度图像"))
        self.isSaveContrastImgCheck.setText(_translate("Form", "是否保留对比度图"))
        self.GaussBlurRadio.setText(_translate("Form", "高斯滤波"))
        self.medianBlurRadio.setText(_translate("Form", "中值滤波"))
        self.averageBlurRadio.setText(_translate("Form", "均值滤波"))
        self.label_12.setText(_translate("Form", "卷积核："))
        self.blurBtn.setText(_translate("Form", "滤波"))
        self.BluredImgBtn.setText(_translate("Form", "滤波图像"))
        self.isSaveBlurImgCheck.setText(_translate("Form", "是否保留滤波图"))
        self.ThresholdRadio.setText(_translate("Form", "全局阈值"))
        self.label.setText(_translate("Form", "阈值大小："))
        self.GaussThresholdRadio.setText(_translate("Form", "自适应高斯阈值"))
        self.MeanThresholdRadio.setText(_translate("Form", "自适应均值阈值"))
        self.OTSUThresholdRadio.setText(_translate("Form", "OTSU阈值"))
        self.label_2.setText(_translate("Form", "区块大小："))
        self.ExecuteThresBtn.setText(_translate("Form", "阈值"))
        self.ThresImgBtn.setText(_translate("Form", "阈值图像"))
        self.isSaveThresImgCheck.setText(_translate("Form", "是否保留阈值图"))
        self.RectificationBtn.setText(_translate("Form", "图像校正"))
        self.isSaveRectifyImgCheck.setText(_translate("Form", "是否保留校正图"))
        self.returnOrignalImgBtn.setText(_translate("Form", "返回原始图片"))
        self.HoughCircleBtn.setText(_translate("Form", "霍夫原检测"))
        self.label_5.setText(_translate("Form", "循环次数："))
        self.MorphRectRadio.setText(_translate("Form", "矩形"))
        self.MorphElliRadio.setText(_translate("Form", "椭圆形"))
        self.MorphCrossRadio.setText(_translate("Form", "十字形"))
        self.label_4.setText(_translate("Form", "核种类："))
        self.label_3.setText(_translate("Form", "核大小："))
        self.isSaveMorphImgCheck.setText(_translate("Form", "是否保留变换图"))
        self.BlackHatBtn.setText(_translate("Form", "黑帽"))
        self.TopHatBtn.setText(_translate("Form", "顶帽"))
        self.DilationBtn.setText(_translate("Form", "膨胀"))
        self.ErosionBtn.setText(_translate("Form", "腐蚀"))
        self.FindRectBtn.setText(_translate("Form", "找矩形"))

